name: hello

description: hello

runs:
  using: "composite"

  steps:
    # - name: Cache foo node_modules
    #   id: cache-foo-node-modules
    #   uses: actions/cache@v3
    #   with:
    #     path: foo/node_modules
    #     key: ${{ runner.os }}-node-${{ hashFiles('foo/package-lock.json') }}
    #     restore-keys: |
    #       ${{ runner.os }}-node-

    - name: Install foo dependencies
      if: steps.cache-foo-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo 'NODE_ENV'
        echo $NODE_ENV
        npm install --prefix foo

    - name: Cache bar node_modules
      id: cache-bar-node-modules
      uses: actions/cache@v3
      with:
        path: bar/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('bar/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
  
    - name: Install bar dependencies
      if: steps.cache-bar-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: npm install --prefix bar
